import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'playwright-report',
      'test-results',
      'storybook-static',
      // Generated by `npx msw init`; served in dev only, never hand-edited.
      'mocks/mockServiceWorker.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.mjs'],
    languageOptions: {
      globals: { URL: 'readonly', process: 'readonly', console: 'readonly' },
    },
  },
  {
    // The offline shell (FE-004) runs in a ServiceWorkerGlobalScope, not a
    // window, so its globals have to be declared rather than assumed.
    files: ['public/sw.js'],
    languageOptions: {
      globals: {
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        Promise: 'readonly',
      },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      // Response types come from the generated client; `any` would silently
      // bypass the contract (.claude/rules/frontend.md).
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
);
