#!/usr/bin/env node
// Generates src/design/tokens.css from src/design/tokens.json.
//
// tokens.json is exported from the Figma file's local variables and styles;
// this script only reshapes it. Figma stays the source of truth, so never edit
// the generated CSS by hand. `npm run tokens:check` regenerates and fails if
// the committed output drifts, the same contract as the API client.
//
// Naming matches the WEB codeSyntax the design side set on each variable:
// `font/title-lg` -> `--font-title-lg`, `radius/pill` -> `--radius-pill`.
// Colour variables carry no codeSyntax, so their path maps the same way:
// `color/text/primary` -> `--color-text-primary`.

import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../src/design/', import.meta.url);
const tokens = JSON.parse(readFileSync(new URL('tokens.json', dir), 'utf8'));

/** `color/text/primary` -> `--color-text-primary` */
const cssVar = (path) => '--' + path.replace(/\//g, '-');

/** Figma line-height keeps its unit: 16px stays px, 100% becomes unitless 1. */
const lineHeight = (value) =>
  value.endsWith('%') ? String(Number(value.slice(0, -1)) / 100) : value;

/** `Body/sm compact` -> `body-sm-compact` */
const styleSlug = (name) => name.toLowerCase().replace(/[/\s]+/g, '-');

const weights = { Regular: 400, Medium: 500, 'Semi Bold': 600, Bold: 700 };

const lines = [
  '/* Generated by scripts/build-tokens.mjs from src/design/tokens.json. Do not edit. */',
  `/* Figma: ${tokens.source.file} (${tokens.source.fileKey}), exported ${tokens.source.exportedAt}. */`,
  '',
  ':root {',
  '  /* Primitive colours. Screens should use the semantic layer below instead. */',
];

for (const [name, hex] of Object.entries(tokens.primitive)) {
  lines.push(`  ${cssVar(name)}: ${hex};`);
}

lines.push('', '  /* Semantic colours. These are what components reference. */');
for (const [name, alias] of Object.entries(tokens.semantic)) {
  lines.push(`  ${cssVar(name)}: var(${cssVar(alias)});`);
}

const groups = {
  space: '  /* Spacing */',
  font: '  /* Font sizes */',
  radius: '  /* Corner radii */',
  border: '  /* Border widths */',
};
for (const [prefix, heading] of Object.entries(groups)) {
  const entries = Object.entries(tokens.number).filter(([n]) =>
    n.startsWith(`${prefix}/`),
  );
  if (entries.length === 0) continue;
  lines.push('', heading);
  for (const [name, value] of entries) {
    lines.push(`  ${cssVar(name)}: ${value}px;`);
  }
}

lines.push('', '  /* Elevation */');
for (const style of tokens.effectStyles) {
  lines.push(
    `  --elevation-${styleSlug(style.name).replace('elevation-', '')}: ${style.shadow};`,
  );
}

lines.push(
  '',
  '  /* Type family */',
  `  --font-family-base: '${tokens.fontFamily}', system-ui, sans-serif;`,
);
lines.push('}');

lines.push(
  '',
  '/* Text styles. Each mirrors a Figma text style; apply with the class or',
  '   compose the custom properties directly. */',
);
for (const style of tokens.textStyles) {
  const slug = styleSlug(style.name);
  lines.push(
    '',
    `.text-${slug} {`,
    `  font-size: var(${cssVar(style.sizeVar)});`,
    `  font-weight: ${weights[style.weight]};`,
    `  line-height: ${lineHeight(style.lineHeight)};`,
    '}',
  );
}

writeFileSync(new URL('tokens.css', dir), lines.join('\n') + '\n');

const counts = {
  primitive: Object.keys(tokens.primitive).length,
  semantic: Object.keys(tokens.semantic).length,
  number: Object.keys(tokens.number).length,
  textStyles: tokens.textStyles.length,
  effectStyles: tokens.effectStyles.length,
};
console.log(
  `tokens.css written: ${counts.primitive} primitive, ${counts.semantic} semantic, ` +
    `${counts.number} numeric, ${counts.textStyles} text styles, ${counts.effectStyles} elevations.`,
);
