// Request-boundary helpers. Mirrors the barrel convention of shared/ui.
export {
  isProblem,
  toProblem,
  PROBLEM_CODES,
  type Problem,
  type ProblemCode,
  type FieldError,
} from './problem.js';
export {
  PROBLEM_POLICY,
  shouldRetry,
  retryDelayMs,
  type ProblemPolicy,
  type RetryPolicy,
  type RecoveryKind,
  type Severity,
  type RetryContext,
} from './problem-policy.js';
export {
  problemPresentation,
  unknownFailurePresentation,
  type ProblemPresentation,
} from './problem-message.js';
export { createQueryClient } from './query-client.js';
export {
  apiBaseUrl,
  currentCsrfToken,
  getApiClient,
  sessionQueryKey,
  currentDeletionToken,
  currentOwnerQueryKey,
  forgetDeletionToken,
  useCreateTrip,
  useCurrentOwner,
  useDeletionStatus,
  useRequestDeletion,
  clearCsrfTokenForTest,
  reissueCsrfToken,
  useCsrfToken,
  useCreateOptimization,
  useDecideOptimization,
  useFeed,
  isRunning,
  optimizationQueryKey,
  useOptimization,
  useOptimizationHistory,
  useTripOptimizationHistory,
  useRevertOptimizationDecision,
  usePlaceSearch,
  usePlaceCrowdForecast,
  usePlaceCrowdForecasts,
  usePost,
  useSavePost,
  useUnsavePost,
  bootstrapSession,
  useSessionBootstrap,
  useTrip,
  useSetItemConstraint,
  useTrips,
  useReplaceTripInterests,
  useUpdateTrip,
  useDeleteTrip,
  useParseTripImport,
  useRemapTripImport,
  useConfirmTripImport,
  type ImportDraftWithETag,
  useTripCandidates,
  useCandidateMatches,
  useAddTripItem,
  useRemoveTripCandidate,
  useRemoveItemConstraint,
  useUpdateTripItem,
  useReorderTripItems,
  useReplaceTripItem,
  useRemoveTripItem,
  useAddTripCandidate,
  useRelatedPlaces,
  useLiveAreas,
  useLiveAreaPlaces,
  useLivePlace,
  liveAreasQueryKey,
  candidatesQueryKey,
  useUpdatePreferences,
  tripQueryKey,
  type TripWithETag,
  type TripMutationWithETag,
} from './session.js';
